[package]
name = "home"
version = "0.5.1" # also update `html_root_url` in `src/lib.rs`
authors = [ "Brian Anderson <andersrb@gmail.com>" ]
documentation = "https://docs.rs/home"
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/brson/home"
description = "Shared definitions of home directories"

[target."cfg(windows)".dependencies.winapi]
version = "0.3"
features = [
    "shlobj",
    "std",
    "winerror",
]
